CREATE TABLE UTENTE(
	ID integer NOT NULL,
	NOME character varying(50),
	COGNOME character varying(50),
	USERNAME character varying(30) UNIQUE,
	PASSWORD character varying(32),
	ENABLED smallint NOT NULL,
	CONSTRAINT pk_USER PRIMARY KEY (ID)
);

CREATE TABLE RUOLO(
	UTENTE_ID integer NOT NULL,
	NOMERUOLO character varying(20),
	CONSTRAINT pk_RUOLO PRIMARY KEY (UTENTE_ID)
);

CREATE TABLE TIPESAME(
	ID integer NOT NULL,
	NOME character varying(50) UNIQUE NOT NULL,
	COD character varying(10) NOT NULL,
	DESCR character varying(100) NOT NULL,
	COSTO numeric,
	CONSTRAINT pk_TIPESAME PRIMARY KEY (ID)
);

CREATE TABLE MEDICO(
	ID integer NOT NULL,
	NOME character varying(50) NOT NULL,
	COGNOME character varying(50) NOT NULL,
	SPECIALIZZAZIONE character varying(30),
	CONSTRAINT pk_MEDICO PRIMARY KEY (ID)
);


CREATE TABLE PREREQUISITO(
	ID integer NOT NULL,
	NOME character varying(30) UNIQUE NOT NULL,
	DESCR character varying(50) NOT NULL,
	CONSTRAINT pk_PREREQUISITO PRIMARY KEY(ID)
);

CREATE TABLE RISULTATO(
	ID integer NOT NULL,
	NOME character varying(30),
	CONSTRAINT pk_RISULTATO PRIMARY KEY(ID)
);


CREATE TABLE ESAME(
	ID integer NOT NULL,
	TIPESAME_ID integer,
	PAZIENTE_ID integer,
	DATAPREN	date NOT NULL,	
	DATAEFFE	date,
	MEDICO_ID integer,
	CONSTRAINT pk_ESAME PRIMARY KEY(ID),
	CONSTRAINT fk_TIPESAMEESAME FOREIGN KEY(TIPESAME_ID) REFERENCES TIPESAME(ID),
	CONSTRAINT fk_PAZIENTE FOREIGN KEY(PAZIENTE_ID) REFERENCES UTENTE(ID),
	CONSTRAINT fk_MEDICO FOREIGN KEY(MEDICO_ID) REFERENCES MEDICO(ID)
);

	
